#!/bin/sh /etc/rc.common

START=10
STOP=90
USE_PROCD=1

PROG=/usr/bin/askey_pwm

start_service() {
	[ -x "$PROG" ] || return 1
	[ ! -L /tmp/pwm ] || return 1
	mkdir -p /tmp/pwm || return 1
	chown root:root /tmp/pwm || return 1
	chmod 700 /tmp/pwm || return 1
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 5 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger pwm
}
