#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

start_service() {
	local enabled
	config_load sbe-services
	config_get_bool enabled watchdog enabled 0
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/sbe-local-watchdog daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger sbe-services
}
